(function(){
  'use strict';
  const G=TwoBodyGeometry,F=EllipsePhantom,$=id=>document.getElementById(id);
  const truth={cx:.04,cy:-.04,a:.92,b:.46,rotation:.48};
  const names=['資料','初始外包絡','初始內包絡','外點排除','反覆更新','最終包絡','輸出 R','誤差界'];
  const titles=['每個量測值是一條弦的長度','投影端點建立初始外包絡 P₀','弦長建立初始內包絡 Q₀','由已知外點收縮外包絡','交替收縮 P 並擴張 Q','得到最終內外包絡','取最終包絡的 Minkowski 中點','由包絡寬度得到 Hausdorff 上界'];
  const C={truth:'#66727d',outer:'#b87914',inner:'#087d75',output:'#8150a1',ray:'#cb4d33',grid:'#e5e9e9'};
  let data,recon,step=0,k=60;
  const f=(x,n=4)=>Number.isFinite(x)?x.toFixed(n):'—';
  const tag=(n,a={},c='')=>`<${n} ${Object.entries(a).map(([x,y])=>`${x}="${y}"`).join(' ')}>${c}</${n}>`;
  const line=(x1,y1,x2,y2,a={})=>tag('line',{x1,y1,x2,y2,...a});
  const text=(x,y,s,a={})=>tag('text',{x,y,...a},s);
  const poly=(p,map,a={})=>p&&p.length>1?tag('polygon',{points:p.map(v=>map(v).join(',')).join(' '),fill:'none',...a}):'';
  const segment=(p,map,a={})=>tag('line',{x1:map(p[0])[0],y1:map(p[0])[1],x2:map(p[1])[0],y2:map(p[1])[1],...a});
  function makeData(views){const ds=.03,K=50,detector=Array.from({length:2*K+1},(_,i)=>(i-K)*ds),angles=Array.from({length:views},(_,j)=>j*Math.PI/views),total=angles.map(phi=>detector.map(s=>F.radon(truth,s,phi)));return{detector,angles,total,ds};}
  function distPoint(p,q){let inside=true,best=Infinity;for(let i=0;i<q.length;i++){const a=q[i],b=q[(i+1)%q.length],e=[b[0]-a[0],b[1]-a[1]],v=[p[0]-a[0],p[1]-a[1]];if(e[0]*v[1]-e[1]*v[0]<-1e-10)inside=false;const t=Math.max(0,Math.min(1,(v[0]*e[0]+v[1]*e[1])/(e[0]*e[0]+e[1]*e[1])));best=Math.min(best,Math.hypot(v[0]-t*e[0],v[1]-t*e[1]));}return inside?0:best;}
  function deriveInner(outer,previous=[]){const segments=[],points=previous.map(v=>[...v]);data.total.forEach((row,j)=>row.forEach((g,i)=>{if(g<=1e-12)return;const iv=G.lineInterval(outer,data.detector[i],data.angles[j]);if(!iv)return;const mandatory=[iv[1]-g,iv[0]+g];if(mandatory[0]<=mandatory[1]-1e-10){const endpoints=mandatory.map(t=>G.pointOnLine(data.detector[i],data.angles[j],t));segments.push({j,k:i,g,outer:iv,mandatory,endpoints});points.push(...endpoints);}}));return{inner:G.hull(points),segments};}
  function refineSingle(initialOuter,initialInner,rounds=4){let outer=initialOuter.map(v=>[...v]),inner=initialInner.map(v=>[...v]);const states=[{round:0,outer:outer.map(v=>[...v]),inner:inner.map(v=>[...v]),cuts:0,bound:.5*Math.max(...outer.map(p=>distPoint(p,inner)))}];for(let round=1;round<=rounds;round++){const frozen=inner.map(v=>[...v]);let cuts=0;data.total.forEach((row,j)=>{let valid=[];row.forEach((g,i)=>{const iv=G.lineInterval(frozen,data.detector[i],data.angles[j]);if(iv&&iv[1]-iv[0]>1e-7&&iv[1]-iv[0]<=g+1e-7)valid.push({i,iv,g});});if(valid.length>16){const chosen=[];for(let n=0;n<16;n++)chosen.push(valid[Math.round(n*(valid.length-1)/15)]);valid=chosen;}valid.forEach(({i,iv,g})=>{const chordUpper=g+5e-7;[iv[1]-chordUpper-1e-8,iv[0]+chordUpper+1e-8].forEach(t=>{const witness=G.pointOnLine(data.detector[i],data.angles[j],t),result=G.excludeShadow(outer,frozen,witness);if(result.changed){outer=result.polygon;cuts++;}});});});inner=deriveInner(outer,inner).inner;const bound=.5*Math.max(...outer.map(p=>distPoint(p,inner)));states.push({round,outer:outer.map(v=>[...v]),inner:inner.map(v=>[...v]),cuts,bound});if(!cuts)break;}return{outer,inner,states};}
  function rebuild(){data=makeData(Number($('views').value));let outer=[[-1.5,-1.5],[1.5,-1.5],[1.5,1.5],[-1.5,1.5]],brackets=[];data.total.forEach((row,j)=>{const pos=row.map((g,i)=>g>1e-12?i:-1).filter(i=>i>=0),lo=data.detector[pos[0]-1],hi=data.detector[pos.at(-1)+1];brackets.push([lo,hi]);outer=G.strip(outer,lo,hi,data.angles[j]);});const seed=deriveInner(outer),refined=refineSingle(outer,seed.inner),output=G.hull(refined.inner.flatMap(q=>refined.outer.map(p=>[(q[0]+p[0])/2,(q[1]+p[1])/2]))),bound=.5*Math.max(...refined.outer.map(p=>distPoint(p,refined.inner)));recon={initialOuter:outer,initialInner:seed.inner,outer:refined.outer,inner:refined.inner,output,bound,brackets,segments:seed.segments,states:refined.states};const best=seed.segments.reduce((a,b)=>(b.mandatory[1]-b.mandatory[0])>(a.mandatory[1]-a.mandatory[0])?b:a);k=best.k;recon.example=best;$('ray').max=String(data.detector.length-1);$('ray').value=String(k);render();}
  function lesson(){const e=recon.example,phi=data.angles[e.j],s=data.detector[k],g=data.total[e.j][k],iv=G.lineInterval(recon.initialOuter,s,phi),mandatory=iv&&g>0?[iv[1]-g,iv[0]+g]:null;let explanation='',formula='',condition='真值只用於畫紅線與事後評估，不進入重建。';if(step===0){explanation='未知物體 D 是密度為 1 的凸體。資料 g(j,k) 是第 j 個方向、第 k 條量測線穿過 D 的弦長。';formula='g(j,k)=length(D∩ℓ(s<sub>k</sub>,φ<sub>j</sub>))';}else if(step===1){explanation='每個方向取第一個與最後一個正值的外側 detector 點。所有保守條帶相交，得到包含 D 的初始外包絡。';formula='P₀=⋂<sub>j</sub>{x: â<sub>j</sub>≤x·θ<sub>j</sub>≤b̂<sub>j</sub>}，　D⊆P₀';}else if(step===2){explanation='若 P₀ 在某條量測線上的區間是 [a,b]，真弦長為 g，則 [b−g,a+g] 是所有可行真弦的共同部分。全部共同部分的凸包形成 Q₀。';formula=iv?`P₀∩ℓ=[${f(iv[0])},${f(iv[1])}]，g=${f(g)}<small>${mandatory&&mandatory[0]<=mandatory[1]?`必存區間=[${f(mandatory[0])},${f(mandatory[1])}]`:'此射線沒有非空必存區間。'}</small>`:'目前射線未穿過 P₀。';}else if(step===3){explanation='已知 Q 在 D 內。對一條量測線，任何長度為 g 且包含 Q 弦的真弦，都不可能碰到共同範圍以外的點；這些點確定在 D 外，可用凸性從 P 切除。';formula='Q⊆D， z∉D  ⟹  {x:z∈conv(Q∪{x})} 可從 P 排除';}else if(step===4){explanation='每輪先用目前 Q 找外點並收縮 P，再由較小的 P 重新計算必存線段、擴張 Q。包含關係在每輪保持。';formula=`Q₀⊆Q₁⊆⋯⊆D⊆⋯⊆P₁⊆P₀<small>${recon.states.slice(1).map(s=>`第 ${s.round} 輪：${s.cuts} 次切除，半寬 ${f(s.bound,6)}`).join('；')}</small>`;}else if(step===5){explanation='更新停止後得到最終 Q 與 P。兩者之間的距離是剩餘幾何不確定性。';formula=`Q⊆D⊆P，　½d<sub>H</sub>(P,Q)=${f(recon.bound,6)}`;}else if(step===6){explanation='輸出取最終包絡的 Minkowski 中點。它保持凸性，不使用橢圓模型，也不是像素閾值。';formula='R=½(Q+P)={(q+p)/2:q∈Q,p∈P}';}else{explanation='由支撐函數 hQ≤hD≤hP 與 hR=(hQ+hP)/2，可直接得到誤差上界。';formula=`d<sub>H</sub>(D,R)≤½d<sub>H</sub>(P,Q)=<strong>${f(recon.bound,6)}</strong>`;condition='此頁使用浮點幾何與有限輪更新；數值界尚未做區間算術認證。';}$('counter').textContent=`STEP ${step+1} / 8`;$('stepTitle').textContent=titles[step];$('explanation').textContent=explanation;$('formula').innerHTML=formula;$('condition').textContent=condition;}
  function drawPlane(){const W=560,H=480,pad=42,ext=1.35,size=H-2*pad,left=(W-size)/2,map=v=>[left+(v[0]+ext)/(2*ext)*size,H-pad-(v[1]+ext)/(2*ext)*size];let out='';for(const t of [-1,-.5,0,.5,1]){const x=map([t,0])[0],y=map([0,t])[1];out+=line(x,pad,x,H-pad,{stroke:C.grid})+line(left,y,left+size,y,{stroke:C.grid});}if(step===1)out+=poly(recon.initialOuter,map,{stroke:C.outer,'stroke-width':3,fill:C.outer,'fill-opacity':.06});if(step===2){out+=poly(recon.initialOuter,map,{stroke:C.outer,'stroke-width':3,fill:'none'});recon.segments.forEach(s=>out+=segment(s.endpoints,map,{stroke:C.inner,'stroke-width':1,opacity:.16}));out+=poly(recon.initialInner,map,{stroke:C.inner,'stroke-width':3,fill:C.inner,'fill-opacity':.13});}if(step===3){out+=poly(recon.initialOuter,map,{stroke:C.outer,'stroke-width':2,'stroke-dasharray':'7 5',fill:'none'});const first=recon.states[Math.min(1,recon.states.length-1)];out+=poly(first.outer,map,{stroke:C.outer,'stroke-width':3,fill:C.outer,'fill-opacity':.06});out+=poly(recon.initialInner,map,{stroke:C.inner,'stroke-width':2.5,fill:'none'});}if(step===4){recon.states.forEach((state,i)=>{out+=poly(state.outer,map,{stroke:C.outer,'stroke-width':i===recon.states.length-1?3:1,opacity:i===recon.states.length-1?1:.22,fill:'none'});out+=poly(state.inner,map,{stroke:C.inner,'stroke-width':i===recon.states.length-1?3:1,opacity:i===recon.states.length-1?1:.22,fill:'none'});});}if(step>=5){out+=poly(recon.outer,map,{stroke:C.outer,'stroke-width':3,fill:C.outer,'fill-opacity':.04});out+=poly(recon.inner,map,{stroke:C.inner,'stroke-width':2.5,fill:'none'});}if(step>=6)out+=poly(recon.output,map,{stroke:C.output,'stroke-width':3,fill:C.output,'fill-opacity':.12});if(step===0||$('truth').checked)out+=poly(F.boundary(truth),map,{stroke:C.truth,'stroke-width':2,'stroke-dasharray':'6 5',fill:step===0?C.truth:'none','fill-opacity':.08});if(step<=2){const e=recon.example,s=data.detector[k],phi=data.angles[e.j],a=G.pointOnLine(s,phi,-2),b=G.pointOnLine(s,phi,2);out+=segment([a,b],map,{stroke:C.ray,'stroke-width':1.8});}$('plane').innerHTML=out;$('planeNote').textContent=step===3?'虛線 P₀；實線是第一輪後的 P':step===4?'淡線到實線：逐輪收縮與擴張':'橘 P · 綠 Q · 紫 R';}
  function drawData(){const W=480,H=250,L=45,R=14,T=15,B=35,cw=(W-L-R)/data.angles.length,ch=(H-T-B)/data.detector.length,max=Math.max(...data.total.flat());let out='';data.total.forEach((row,j)=>row.forEach((g,i)=>{const alpha=max?Math.min(1,g/max):0;out+=tag('rect',{x:L+j*cw,y:T+(data.detector.length-1-i)*ch,width:cw+.2,height:ch+.2,fill:`rgba(8,125,117,${alpha})`});}));const ej=recon.example.j;out+=tag('rect',{x:L+ej*cw,y:T,width:cw,height:H-T-B,fill:'none',stroke:C.ray,'stroke-width':2});out+=text(L+(W-L-R)/2,H-8,'角度 φ',{'text-anchor':'middle'})+text(8,T+8,'s');$('sinogram').innerHTML=out;$('matrixSize').textContent=`${data.angles.length} × ${data.detector.length}`;const e=recon.example,phi=data.angles[e.j],s=data.detector[k],g=data.total[e.j][k],iv=G.lineInterval(recon.outer,s,phi),truthIv=F.chord(truth,s,phi),m=iv&&g>0?[iv[1]-g,iv[0]+g]:null,map=t=>45+(t+1.5)/3*390;let q=line(45,110,435,110,{stroke:'#9aa7ad','stroke-width':2})+text(45,28,`φ = ${f(phi*180/Math.PI,1)}°，s = ${f(s,2)}，g = ${f(g)}`);if(iv)q+=line(map(iv[0]),72,map(iv[1]),72,{stroke:C.outer,'stroke-width':10})+text(16,76,'P');if(truthIv&&$('truth').checked)q+=line(map(truthIv[0]),110,map(truthIv[1]),110,{stroke:C.truth,'stroke-width':8,'stroke-dasharray':'5 4'})+text(16,114,'D');if(m&&m[0]<=m[1])q+=line(map(m[0]),150,map(m[1]),150,{stroke:C.inner,'stroke-width':10})+text(16,154,'必存');$('interval').innerHTML=q;$('sValue').textContent=f(s,2);$('rayNote').textContent='拖動 s 只改變右下方的一維解說；重建 P、Q、R 使用整份固定資料。';}
  function render(){lesson();drawPlane();drawData();[...$('steps').children].forEach((b,i)=>b.setAttribute('aria-current',i===step?'step':'false'));$('previous').disabled=step===0;$('next').disabled=step===7;}
  $('steps').innerHTML=names.map((n,i)=>`<button data-step="${i}" aria-current="${i===0?'step':'false'}"><span>${i+1}</span>${n}</button>`).join('');$('steps').addEventListener('click',e=>{const b=e.target.closest('button');if(b){step=Number(b.dataset.step);render();}});$('previous').addEventListener('click',()=>{step=Math.max(0,step-1);render();});$('next').addEventListener('click',()=>{step=Math.min(7,step+1);render();});$('views').addEventListener('change',rebuild);$('truth').addEventListener('change',render);$('ray').addEventListener('input',()=>{k=Number($('ray').value);render();});rebuild();
})();
