(function(){
  'use strict';
  const G=TwoBodyGeometry,F=EllipsePhantom,$=id=>document.getElementById(id);
  const truth={cx:.04,cy:-.04,a:.92,b:.46,rotation:.48};
  const names=['資料','投影支撐','外包絡 P','必存線段','內包絡 Q','輸出 R','誤差界'];
  const titles=['模型：每個數字是一條弦的長度','先找每個方向的投影範圍','條帶相交得到外包絡','一條射線能確定哪一段必在物體內？','彙整全部必存線段','在內、外包絡之間選一個重建','得到不需要真值的 Hausdorff 上界'];
  const C={truth:'#66727d',outer:'#b87914',inner:'#087d75',output:'#8150a1',ray:'#cb4d33',grid:'#e5e9e9'};
  let data,recon,step=0,k=60;
  const f=(x,n=4)=>Number.isFinite(x)?x.toFixed(n):'—';
  const tag=(n,a={},c='')=>`<${n} ${Object.entries(a).map(([x,y])=>`${x}="${y}"`).join(' ')}>${c}</${n}>`;
  const line=(x1,y1,x2,y2,a={})=>tag('line',{x1,y1,x2,y2,...a});
  const text=(x,y,s,a={})=>tag('text',{x,y,...a},s);
  const poly=(p,map,a={})=>p&&p.length>1?tag('polygon',{points:p.map(v=>map(v).join(',')).join(' '),fill:'none',...a}):'';
  const segment=(p,map,a={})=>tag('line',{x1:map(p[0])[0],y1:map(p[0])[1],x2:map(p[1])[0],y2:map(p[1])[1],...a});
  function makeData(views){const ds=.03,K=50,detector=Array.from({length:2*K+1},(_,i)=>(i-K)*ds),angles=Array.from({length:views},(_,j)=>j*Math.PI/views),total=angles.map(phi=>detector.map(s=>F.radon(truth,s,phi)));return{detector,angles,total,ds};}
  function distPoint(p,q){let inside=true,best=Infinity;for(let i=0;i<q.length;i++){const a=q[i],b=q[(i+1)%q.length],e=[b[0]-a[0],b[1]-a[1]],v=[p[0]-a[0],p[1]-a[1]];if(e[0]*v[1]-e[1]*v[0]<-1e-10)inside=false;const t=Math.max(0,Math.min(1,(v[0]*e[0]+v[1]*e[1])/(e[0]*e[0]+e[1]*e[1])));best=Math.min(best,Math.hypot(v[0]-t*e[0],v[1]-t*e[1]));}return inside?0:best;}
  function rebuild(){data=makeData(Number($('views').value));let outer=[[-1.5,-1.5],[1.5,-1.5],[1.5,1.5],[-1.5,1.5]],brackets=[];data.total.forEach((row,j)=>{const pos=row.map((g,i)=>g>1e-12?i:-1).filter(i=>i>=0),lo=data.detector[pos[0]-1],hi=data.detector[pos.at(-1)+1];brackets.push([lo,hi]);outer=G.strip(outer,lo,hi,data.angles[j]);});const segments=[],points=[];data.total.forEach((row,j)=>row.forEach((g,i)=>{if(g<=1e-12)return;const iv=G.lineInterval(outer,data.detector[i],data.angles[j]);if(!iv)return;const mandatory=[iv[1]-g,iv[0]+g];if(mandatory[0]<=mandatory[1]-1e-10){const endpoints=mandatory.map(t=>G.pointOnLine(data.detector[i],data.angles[j],t));segments.push({j,k:i,g,outer:iv,mandatory,endpoints});points.push(...endpoints);}}));const inner=G.hull(points),output=G.hull(inner.flatMap(q=>outer.map(p=>[(q[0]+p[0])/2,(q[1]+p[1])/2]))),bound=.5*Math.max(...outer.map(p=>distPoint(p,inner)));recon={outer,inner,output,bound,brackets,segments};const best=segments.reduce((a,b)=>(b.mandatory[1]-b.mandatory[0])>(a.mandatory[1]-a.mandatory[0])?b:a);k=best.k;recon.example=best;$('ray').max=String(data.detector.length-1);$('ray').value=String(k);render();}
  function lesson(){const e=recon.example,phi=data.angles[e.j],s=data.detector[k],g=data.total[e.j][k],iv=G.lineInterval(recon.outer,s,phi),mandatory=iv&&g>0?[iv[1]-g,iv[0]+g]:null;let explanation='',formula='',condition='橢圓參數與真值邊界只用於產生資料與畫對照，不進入重建。';if(step===0){explanation='未知物體 D 是一個密度為 1 的凸體。每個資料 g(j,k) 是量測線穿過 D 的長度；把所有角度與 detector 位置排起來就是 sinogram。';formula='g(j,k) = R1<sub>D</sub>(s<sub>k</sub>,φ<sub>j</sub>) = length(D ∩ ℓ(s<sub>k</sub>,φ<sub>j</sub>))';}else if(step===1){explanation='固定一個方向，正值樣本的位置告訴我們投影支撐。第一個與最後一個正值外側各取一個 detector 點，形成保守條帶。';formula=`â<sub>j</sub> = s<sub>k⁻−1</sub>，b̂<sub>j</sub> = s<sub>k⁺+1</sub><small>因此 â<sub>j</sub> ≤ min x·θ<sub>j</sub>，max x·θ<sub>j</sub> ≤ b̂<sub>j</sub>。</small>`;}else if(step===2){explanation='把全部方向的保守條帶相交，得到凸多邊形 P。P 一定包含真實凸體，但通常有角落與額外面積。';formula='P = ⋂<sub>j</sub>{x : â<sub>j</sub> ≤ x·θ<sub>j</sub> ≤ b̂<sub>j</sub>}，　D ⊆ P';}else if(step===3){explanation='把目前射線攤成 t 軸。P 的弦是 [a,b]，真實弦 [u,v] 位於其中，長度 v−u=g。所有可行真弦的共同部分就是 [b−g,a+g]；若左右顛倒，這條射線沒有可保證的內部。';formula=iv?`P∩ℓ = [${f(iv[0])}, ${f(iv[1])}]，g = ${f(g)}<small>${mandatory&&mandatory[0]<=mandatory[1]?`必存區間 = [${f(mandatory[0])}, ${f(mandatory[1])}]`:'此射線沒有非空必存區間。'}</small>`:'目前射線未穿過 P。';condition='這正對應文獻的 core construction C(E,p) 在單一弦段情形下的幾何內容；本頁使用它形成一輪內包絡。';}else if(step===4){explanation='對全部量測射線重複上一步，收集所有必存線段。因為 D 是凸的，這些線段的凸包仍留在 D 內，形成內包絡 Q。';formula=`Q = conv(所有必存線段)，　Q ⊆ D ⊆ P<small>本次共有 ${recon.segments.length} 條非空必存線段。</small>`;}else if(step===5){explanation='已知真實物體夾在 Q 與 P 之間。我們用 Minkowski 中點體作為一個對稱的代表輸出；它不是像素平均，也不是橢圓擬合。';formula='R = ½(Q+P) = {(q+p)/2 : q∈Q, p∈P}';}else{explanation='凸緊集合的 Hausdorff 距離可由支撐函數表示。因為 hQ≤hD≤hP，而 hR=(hQ+hP)/2，所以 D 到 R 的最大偏差不超過 P 與 Q 間距的一半。';formula=`d<sub>H</sub>(D,R) ≤ ½d<sub>H</sub>(P,Q) = <strong>${f(recon.bound,6)}</strong><small>右側只由重建出的 P、Q 計算，不使用真值。</small>`;condition='這個界的前提是 Q ⊆ D ⊆ P。浮點網頁用來解說，不是嚴格區間算術認證。';}$('counter').textContent=`STEP ${step+1} / 7`;$('stepTitle').textContent=titles[step];$('explanation').textContent=explanation;$('formula').innerHTML=formula;$('condition').textContent=condition;}
  function drawPlane(){const W=560,H=480,pad=42,ext=1.35,size=H-2*pad,left=(W-size)/2,map=v=>[left+(v[0]+ext)/(2*ext)*size,H-pad-(v[1]+ext)/(2*ext)*size];let out='';for(const t of [-1,-.5,0,.5,1]){const x=map([t,0])[0],y=map([0,t])[1];out+=line(x,pad,x,H-pad,{stroke:C.grid})+line(left,y,left+size,y,{stroke:C.grid});}if(step===1){const e=recon.example,[lo,hi]=recon.brackets[e.j],strip=G.strip([[-1.35,-1.35],[1.35,-1.35],[1.35,1.35],[-1.35,1.35]],lo,hi,data.angles[e.j]);out+=poly(strip,map,{stroke:C.outer,'stroke-width':2.5,fill:C.outer,'fill-opacity':.12});}if(step>=2)out+=poly(recon.outer,map,{stroke:C.outer,'stroke-width':3,fill:C.outer,'fill-opacity':.05});if(step===3){const e=recon.example,s=data.detector[k],phi=data.angles[e.j],iv=G.lineInterval(recon.outer,s,phi),g=data.total[e.j][k],m=iv?[iv[1]-g,iv[0]+g]:null;if(iv)out+=segment(iv.map(t=>G.pointOnLine(s,phi,t)),map,{stroke:C.outer,'stroke-width':9,opacity:.5});if(m&&m[0]<=m[1])out+=segment(m.map(t=>G.pointOnLine(s,phi,t)),map,{stroke:C.inner,'stroke-width':10});}if(step===4){recon.segments.forEach(s=>out+=segment(s.endpoints,map,{stroke:C.inner,'stroke-width':1,opacity:.18}));out+=poly(recon.inner,map,{stroke:C.inner,'stroke-width':3,fill:C.inner,'fill-opacity':.13});}if(step>=5){out+=poly(recon.inner,map,{stroke:C.inner,'stroke-width':2.5,fill:'none'});out+=poly(recon.output,map,{stroke:C.output,'stroke-width':3,fill:C.output,'fill-opacity':.09});}if(step<2||$('truth').checked)out+=poly(F.boundary(truth),map,{stroke:C.truth,'stroke-width':2,'stroke-dasharray':'6 5',fill:step===0?C.truth:'none','fill-opacity':.08});if(step<=3){const e=recon.example,s=data.detector[k],phi=data.angles[e.j],a=G.pointOnLine(s,phi,-2),b=G.pointOnLine(s,phi,2);out+=segment([a,b],map,{stroke:C.ray,'stroke-width':1.8});}$('plane').innerHTML=out;$('planeNote').textContent=step===1?'橘色是本方向的保守條帶':step<2?'真值只供教學':step===3?'綠色是共同必存段':'橘 P · 綠 Q · 紫 R';}
  function drawData(){const W=480,H=250,L=45,R=14,T=15,B=35,cw=(W-L-R)/data.angles.length,ch=(H-T-B)/data.detector.length,max=Math.max(...data.total.flat());let out='';data.total.forEach((row,j)=>row.forEach((g,i)=>{const alpha=max?Math.min(1,g/max):0;out+=tag('rect',{x:L+j*cw,y:T+(data.detector.length-1-i)*ch,width:cw+.2,height:ch+.2,fill:`rgba(8,125,117,${alpha})`});}));const ej=recon.example.j;out+=tag('rect',{x:L+ej*cw,y:T,width:cw,height:H-T-B,fill:'none',stroke:C.ray,'stroke-width':2});out+=text(L+(W-L-R)/2,H-8,'角度 φ',{'text-anchor':'middle'})+text(8,T+8,'s');$('sinogram').innerHTML=out;$('matrixSize').textContent=`${data.angles.length} × ${data.detector.length}`;const e=recon.example,phi=data.angles[e.j],s=data.detector[k],g=data.total[e.j][k],iv=G.lineInterval(recon.outer,s,phi),truthIv=F.chord(truth,s,phi),m=iv&&g>0?[iv[1]-g,iv[0]+g]:null,map=t=>45+(t+1.5)/3*390;let q=line(45,110,435,110,{stroke:'#9aa7ad','stroke-width':2})+text(45,28,`φ = ${f(phi*180/Math.PI,1)}°，s = ${f(s,2)}，g = ${f(g)}`);if(iv)q+=line(map(iv[0]),72,map(iv[1]),72,{stroke:C.outer,'stroke-width':10})+text(16,76,'P');if(truthIv&&$('truth').checked)q+=line(map(truthIv[0]),110,map(truthIv[1]),110,{stroke:C.truth,'stroke-width':8,'stroke-dasharray':'5 4'})+text(16,114,'D');if(m&&m[0]<=m[1])q+=line(map(m[0]),150,map(m[1]),150,{stroke:C.inner,'stroke-width':10})+text(16,154,'必存');$('interval').innerHTML=q;$('sValue').textContent=f(s,2);$('rayNote').textContent='拖動 s 只改變右下方的一維解說；重建 P、Q、R 使用整份固定資料。';}
  function render(){lesson();drawPlane();drawData();[...$('steps').children].forEach((b,i)=>b.setAttribute('aria-current',i===step?'step':'false'));$('previous').disabled=step===0;$('next').disabled=step===6;}
  $('steps').innerHTML=names.map((n,i)=>`<button data-step="${i}" aria-current="${i===0?'step':'false'}"><span>${i+1}</span>${n}</button>`).join('');$('steps').addEventListener('click',e=>{const b=e.target.closest('button');if(b){step=Number(b.dataset.step);render();}});$('previous').addEventListener('click',()=>{step=Math.max(0,step-1);render();});$('next').addEventListener('click',()=>{step=Math.min(6,step+1);render();});$('views').addEventListener('change',rebuild);$('truth').addEventListener('change',render);$('ray').addEventListener('input',()=>{k=Number($('ray').value);render();});rebuild();
})();
